services:
  db:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: userdata
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "1234:3306"
    volumes:
      - ./database_output:/docker-entrypoint-initdb.d

volumes:
  database: